export type {
  APIEndpoint,
  ArchitectureEdge,
  ArchitectureNodeType,
  ArchitectureReview,
  ArchitectureReviewFinding,
  ArchitectureReviewInput,
  Assumption,
  DataModel,
  DataStore,
  ExternalSystem,
  FailureScenario,
  MessageSystem,
  ScaleInput,
  Service,
  SystemDesign,
  SystemDesignInput,
  TechnologyDecision,
  Tradeoff,
} from "@/lib/architecture/validation";
