import type { SystemDesign } from "@/lib/architecture/validation";
import { systemDesignSchema } from "@/lib/architecture/validation";
import { DESIGN_TEMPLATES } from "@/lib/projects/templates";
import { applyDeterministicCapacity } from "@/lib/capacity/calculations";

const ecommerce: SystemDesign = systemDesignSchema.parse({
  title: "Scalable E-commerce Platform",
  summary:
    "A request-driven commerce platform with a search-optimized catalog, a strongly consistent checkout path, and asynchronous post-order processing. Browse and search are cacheable and independently scalable. The money path — cart snapshot, order creation, and payment capture — stays synchronous and transactional; inventory reservation, email, and search indexing happen off the critical path.",
  assumptions: [
    {
      name: "Requests per user per day",
      value: "50",
      rationale: "Browse-heavy sessions with a smaller checkout funnel.",
    },
    {
      name: "Peak multiplier",
      value: "5",
      rationale: "Flash sales and evening traffic, not a flat diurnal curve.",
    },
    {
      name: "Read/write ratio",
      value: "30:1",
      rationale: "Catalog and search dominate; checkout is a thin slice of traffic.",
    },
    {
      name: "Average request size",
      value: "1200 bytes",
      rationale: "JSON APIs plus modest product payloads; media is on CDN, not these APIs.",
    },
  ],
  requirements: {
    functional: [
      "User authentication",
      "Product catalog",
      "Product search",
      "Cart",
      "Checkout",
      "Payment",
      "Order tracking",
    ],
    nonFunctional: [
      "99.99% availability",
      "Low latency catalog browsing",
      "Horizontal scalability",
      "Fault tolerance on non-checkout paths",
    ],
  },
  capacity: { source: "calculated" },
  services: [
    {
      id: "web-client",
      name: "Web Client",
      type: "client",
      description: "Shopper storefront and account UI.",
      responsibilities: ["Browse catalog", "Manage cart", "Checkout"],
      technology: "Next.js",
      scalingStrategy: "CDN-backed static assets; no sticky sessions required.",
      failureBehavior: "Read-only browsing can continue from cached catalog pages.",
    },
    {
      id: "cdn",
      name: "CDN",
      type: "cdn",
      description: "Caches storefront assets and cacheable catalog responses.",
      responsibilities: ["Edge caching", "TLS termination for static content"],
      technology: "CloudFront / Fastly",
      scalingStrategy: "Globally anycast; invalidate on catalog publish.",
      failureBehavior: "Origin shield absorbs origin outages for cacheable GETs.",
    },
    {
      id: "load-balancer",
      name: "Load Balancer",
      type: "load_balancer",
      description: "Distributes API traffic across gateway replicas.",
      responsibilities: ["L7 routing", "Health checks"],
      technology: "AWS ALB",
      scalingStrategy: "Managed autoscaling.",
      failureBehavior: "Unhealthy targets are removed automatically.",
    },
    {
      id: "api-gateway",
      name: "API Gateway",
      type: "gateway",
      description: "Authn/authz edge, rate limits, and request routing.",
      responsibilities: ["JWT validation", "Rate limiting", "Routing"],
      technology: "Kong / Envoy",
      scalingStrategy: "Horizontal replicas behind the load balancer.",
      failureBehavior: "Fail closed on auth errors; shed load with 429s.",
    },
    {
      id: "auth-service",
      name: "Authentication Service",
      type: "auth",
      description: "Issues sessions and tokens for shoppers.",
      responsibilities: ["Signup/login", "Token issuance", "Account recovery"],
      technology: "Node.js",
      scalingStrategy: "Stateless tokens; Redis for refresh-token revocation.",
      failureBehavior: "Existing JWTs remain valid until expiry if auth is down.",
    },
    {
      id: "catalog-service",
      name: "Catalog Service",
      type: "service",
      description: "Source of truth for product data used by browse and checkout.",
      responsibilities: ["Product CRUD", "Price reads", "Publish catalog events"],
      technology: "Go",
      scalingStrategy: "Read replicas; cache hot product pages.",
      failureBehavior: "Serve stale catalog from Redis/CDN if primary is degraded.",
    },
    {
      id: "search-service",
      name: "Search Service",
      type: "service",
      description: "Query interface over the search index, not the OLTP database.",
      responsibilities: ["Full-text search", "Facets", "Autocomplete"],
      technology: "Java",
      scalingStrategy: "Stateless query nodes; scale index cluster separately.",
      failureBehavior: "Fallback to simple DB LIKE is not used; return degraded empty/cached results.",
    },
    {
      id: "cart-service",
      name: "Cart Service",
      type: "service",
      description: "Ephemeral cart state keyed by user or anonymous session.",
      responsibilities: ["Add/update items", "Price snapshot", "Cart expiry"],
      technology: "Go",
      scalingStrategy: "Redis-backed; no sticky routing.",
      failureBehavior: "Cart writes fail closed; users can retry. No silent data loss to SQL.",
    },
    {
      id: "order-service",
      name: "Order Service",
      type: "service",
      description: "Creates orders, owns order state machine, publishes domain events.",
      responsibilities: ["Create orders", "Maintain order state", "Publish order events"],
      technology: "Spring Boot",
      scalingStrategy: "Horizontal scaling behind the API gateway; shard-unneeded at 1M DAU.",
      failureBehavior:
        "Orders are persisted before publishing events. Kafka publishing uses retry + dead-letter handling.",
    },
    {
      id: "payment-service",
      name: "Payment Service",
      type: "service",
      description: "Idempotent payment orchestration against the PSP.",
      responsibilities: ["Authorize/capture", "Refunds", "Webhook handling"],
      technology: "Kotlin",
      scalingStrategy: "Low QPS relative to browse; scale for webhook bursts.",
      failureBehavior: "Idempotency keys prevent double charge on retry.",
    },
  ],
  dataStores: [
    {
      id: "postgres",
      name: "PostgreSQL",
      type: "database",
      description: "System of record for users, orders, payments metadata, and catalog writes.",
      responsibilities: ["Transactional checkout", "Order history"],
      technology: "PostgreSQL",
      scalingStrategy: "Primary + read replicas; connection pooling via PgBouncer.",
      dataCharacteristics: "Relational, strongly consistent, modest write rate vs reads.",
      failureBehavior: "Checkout fails closed. Reads can use replicas with bounded lag.",
    },
    {
      id: "redis",
      name: "Redis",
      type: "cache",
      description: "Carts, sessions, and hot product cache.",
      responsibilities: ["Cart storage", "Rate-limit counters", "Product cache"],
      technology: "Redis",
      scalingStrategy: "Cluster mode; carts keyed by user id.",
      dataCharacteristics: "Ephemeral; TTL on carts.",
      failureBehavior: "Cache miss falls back to PostgreSQL for products; carts become unavailable.",
    },
    {
      id: "opensearch",
      name: "OpenSearch",
      type: "search",
      description: "Denormalized product search index.",
      responsibilities: ["Inverted index", "Facets"],
      technology: "OpenSearch",
      scalingStrategy: "Index replicas; async updates from catalog events.",
      dataCharacteristics: "Eventually consistent with catalog by seconds.",
      failureBehavior: "Search degraded; browse by category from catalog still works.",
    },
    {
      id: "object-storage",
      name: "Object Storage",
      type: "storage",
      description: "Product images and generated assets.",
      responsibilities: ["Blob storage", "Versioned objects"],
      technology: "S3",
      scalingStrategy: "Unlimited object store; CDN in front.",
      dataCharacteristics: "Immutable blobs with catalog references.",
      failureBehavior: "Image misses show placeholders; checkout unaffected.",
    },
  ],
  messageSystems: [
    {
      id: "kafka",
      name: "Kafka",
      type: "queue",
      description: "Domain events for orders, catalog changes, and search indexing.",
      responsibilities: ["Order events", "Catalog updates", "Outbox drain"],
      technology: "Kafka",
      scalingStrategy: "Partition by entity id (orderId / productId).",
      failureBehavior: "Producers retry; outbox retains unpublished events.",
    },
  ],
  externalSystems: [
    {
      id: "psp",
      name: "Payment Provider",
      type: "external",
      description: "Card/wallet processor.",
      responsibilities: ["Authorize", "Capture", "Webhooks"],
      technology: "Stripe",
      scalingStrategy: "External; circuit-break and queue retries.",
      failureBehavior: "Checkout waits on authorization timeout then marks payment pending/failed.",
    },
  ],
  architectureEdges: [
    { id: "e1", from: "web-client", to: "cdn", label: "HTTPS", protocol: "HTTP" },
    { id: "e2", from: "cdn", to: "load-balancer", label: "HTTP", protocol: "HTTP" },
    { id: "e3", from: "load-balancer", to: "api-gateway", label: "HTTP", protocol: "HTTP" },
    { id: "e4", from: "api-gateway", to: "auth-service", label: "HTTP", protocol: "HTTP" },
    { id: "e5", from: "api-gateway", to: "catalog-service", label: "HTTP", protocol: "HTTP" },
    { id: "e6", from: "api-gateway", to: "search-service", label: "HTTP", protocol: "HTTP" },
    { id: "e7", from: "api-gateway", to: "cart-service", label: "HTTP", protocol: "HTTP" },
    { id: "e8", from: "api-gateway", to: "order-service", label: "HTTP", protocol: "HTTP" },
    { id: "e9", from: "order-service", to: "payment-service", label: "gRPC", protocol: "gRPC" },
    { id: "e10", from: "catalog-service", to: "postgres", label: "SQL", protocol: "SQL" },
    { id: "e11", from: "order-service", to: "postgres", label: "Write", protocol: "SQL" },
    { id: "e12", from: "cart-service", to: "redis", label: "Read/Write", protocol: "Redis" },
    { id: "e13", from: "search-service", to: "opensearch", label: "Query", protocol: "HTTP" },
    { id: "e14", from: "catalog-service", to: "kafka", label: "Async", protocol: "Kafka" },
    { id: "e15", from: "order-service", to: "kafka", label: "Kafka", protocol: "Kafka" },
    { id: "e16", from: "payment-service", to: "psp", label: "HTTPS", protocol: "HTTP" },
    { id: "e17", from: "cdn", to: "object-storage", label: "Read", protocol: "HTTP" },
    { id: "e18", from: "auth-service", to: "redis", label: "Session", protocol: "Redis" },
  ],
  apis: [
    {
      method: "POST",
      path: "/orders",
      description: "Create an order from the current cart.",
      request: { items: [{ sku: "SKU-1", quantity: 1 }], paymentMethodId: "pm_123" },
      response: { orderId: "ord_123", status: "PENDING" },
      authentication: "JWT",
      idempotency: "Required (Idempotency-Key header)",
    },
    {
      method: "GET",
      path: "/orders/{id}",
      description: "Fetch order status for tracking.",
      request: {},
      response: { orderId: "ord_123", status: "PAID" },
      authentication: "JWT",
      idempotency: "Not required",
    },
    {
      method: "GET",
      path: "/search",
      description: "Product search with filters.",
      request: { q: "running shoes", limit: 20 },
      response: { items: [], total: 0 },
      authentication: "Optional",
      idempotency: "Not required",
    },
  ],
  dataModel: [
    {
      name: "User",
      description: "Shopper account",
      fields: [
        { name: "id", type: "uuid", description: "Primary key" },
        { name: "email", type: "string", description: "Unique" },
        { name: "created_at", type: "timestamptz", description: "" },
      ],
      relationships: [{ target: "Order", type: "has_many", description: "Orders placed" }],
    },
    {
      name: "Product",
      fields: [
        { name: "id", type: "uuid", description: "" },
        { name: "sku", type: "string", description: "Unique SKU" },
        { name: "name", type: "string", description: "" },
        { name: "price_cents", type: "int", description: "Current list price" },
      ],
      relationships: [{ target: "OrderItem", type: "has_many", description: "" }],
    },
    {
      name: "Order",
      fields: [
        { name: "id", type: "uuid", description: "" },
        { name: "user_id", type: "uuid", description: "" },
        { name: "status", type: "enum", description: "PENDING|PAID|FAILED|SHIPPED" },
        { name: "total_cents", type: "int", description: "" },
      ],
      relationships: [
        { target: "User", type: "belongs_to", description: "" },
        { target: "OrderItem", type: "has_many", description: "" },
      ],
    },
    {
      name: "OrderItem",
      fields: [
        { name: "order_id", type: "uuid", description: "" },
        { name: "product_id", type: "uuid", description: "" },
        { name: "quantity", type: "int", description: "" },
        { name: "price_cents", type: "int", description: "Snapshot at purchase" },
      ],
      relationships: [
        { target: "Order", type: "belongs_to", description: "" },
        { target: "Product", type: "belongs_to", description: "" },
      ],
    },
  ],
  technologyDecisions: [
    {
      technology: "PostgreSQL",
      why: "Strong consistency and relational transactions are useful for orders and payments.",
      alternative: "MongoDB",
      whyNot: "The core workload has relational transactional requirements.",
    },
    {
      technology: "Redis",
      why: "Carts and hot product pages need sub-millisecond access and TTLs.",
      alternative: "PostgreSQL only",
      whyNot: "Checkout-adjacent cart traffic would contend with OLTP connections.",
    },
    {
      technology: "Kafka",
      why: "Decouples search indexing and post-order workflows from checkout latency.",
      alternative: "Synchronous service-to-service calls",
      whyNot: "A search outage should not fail order creation.",
    },
    {
      technology: "OpenSearch",
      why: "Faceted full-text search is a different access pattern than OLTP.",
      alternative: "Postgres FTS",
      whyNot: "Faceted catalog search at this scale is a poor fit for the primary database.",
    },
    {
      technology: "Object storage",
      why: "Images are large immutable blobs that belong on cheap object storage + CDN.",
      alternative: "Database BLOBs",
      whyNot: "BLOBs inflate backups and compete with transactional I/O.",
    },
    {
      technology: "CDN",
      why: "Most catalog traffic is cacheable and geographically distributed.",
      alternative: "Origin-only",
      whyNot: "Origin fan-out during peaks is expensive and slow.",
    },
  ],
  tradeoffs: [
    {
      decision: "Kafka instead of synchronous service-to-service communication for search and notifications",
      benefit: "Loose coupling and asynchronous processing",
      cost: "Eventual consistency and operational complexity",
      whenToReconsider:
        "If traffic or asynchronous workflows are low, a simpler synchronous architecture may be preferable.",
    },
    {
      decision: "Keep checkout on PostgreSQL rather than a dedicated order store",
      benefit: "One transactional boundary for order + payment metadata",
      cost: "A noisy catalog write path could contend for the same cluster if not isolated",
      whenToReconsider: "When order write QPS or data retention forces a split (CQRS / separate order DB).",
    },
  ],
  failureScenarios: [
    {
      scenario: "Redis unavailable",
      impact: "Carts cannot be read or written; product cache misses increase Postgres load.",
      detection: "Redis ping failures, cart error rate, cache hit ratio collapse.",
      mitigation: "Fail carts closed; serve products from DB/CDN; protect Postgres with load shedding.",
      recovery: "Rebuild cache; carts with TTL are lost unless a write-through design is added later.",
    },
    {
      scenario: "Kafka unavailable",
      impact: "Event publishing is delayed. Search and emails lag.",
      detection: "Producer timeouts, outbox table growth.",
      mitigation: "Persist events using an outbox pattern.",
      recovery: "Replay pending events once Kafka recovers.",
    },
    {
      scenario: "Database unavailable",
      impact: "Checkout and account operations fail. Cached catalog may still browse.",
      detection: "Connection pool exhaustion, replica lag, error budget burn.",
      mitigation: "Fail closed on writes; keep CDN cache for reads.",
      recovery: "Failover to replica if primary is lost; verify no split-brain.",
    },
    {
      scenario: "Payment service timeout",
      impact: "Orders stuck in PENDING; risk of double charge if retried naively.",
      detection: "p95 payment latency, webhook lag.",
      mitigation: "Idempotency keys; PENDING state; reconcile via webhooks.",
      recovery: "Async capture/reconcile job.",
    },
    {
      scenario: "Traffic spike",
      impact: "Search and catalog latency rise; checkout pool saturation.",
      detection: "RPS, queue depth, p95 latency.",
      mitigation: "CDN caching, rate limits, checkout isolation pool.",
      recovery: "Autoscale read path; keep write path protected.",
    },
  ],
  scalingStrategy: [
    "Cache catalog pages at the CDN.",
    "Scale search independently of checkout.",
    "Isolate PostgreSQL connection pools for checkout vs browse.",
    "Partition Kafka by order/product id.",
  ],
  securityConsiderations: [
    "JWT at the gateway; short-lived access tokens.",
    "PCI data never stored; PSP tokens only.",
    "Idempotency keys on payment and order creation.",
    "Least-privilege DB roles per service.",
  ],
  observability: {
    metrics: [
      "Request rate",
      "Error rate",
      "Latency",
      "Queue depth",
      "Database CPU",
      "Cache hit ratio",
    ],
    logs: [
      "Order state transitions with orderId",
      "Payment idempotency key outcomes",
      "Catalog publish events",
    ],
    traces: [
      "Checkout: gateway → order → payment → PSP",
      "Search: gateway → search → OpenSearch",
    ],
    alerts: [
      "p95 latency > 500ms",
      "Error rate > 2%",
      "Kafka consumer lag > threshold",
      "Database connections > 80%",
    ],
  },
});

const rideshare: SystemDesign = systemDesignSchema.parse({
  title: "RideGrid Ride Sharing System",
  summary:
    "A geo-partitioned matching system. Driver location is a high-write stream kept in Redis with short TTL; trip state, quotes, and billing stay in PostgreSQL. Matching is a dedicated service so a pricing or tracking outage cannot stall dispatch. City cells fail independently, and driver assignment uses compare-and-set so a partition cannot double-book a driver.",
  assumptions: [
    {
      name: "Requests per user per day",
      value: "12",
      rationale: "Open app, request, track, complete — plus a burst of location pings that are counted separately from API RPS.",
    },
    {
      name: "Peak multiplier",
      value: "6",
      rationale: "Rush hour is a several-times spike, not a gentle diurnal curve.",
    },
    {
      name: "Read/write ratio",
      value: "20:1",
      rationale: "Location writes dominate the data plane; rider request APIs are relatively rare.",
    },
    {
      name: "Location freshness SLO",
      value: "3 seconds",
      rationale: "Matching quality collapses if the location store is stale.",
    },
  ],
  requirements: {
    functional: ["Driver location", "Ride requests", "Matching", "Pricing", "Trip tracking"],
    nonFunctional: ["Matching p95 < 2s", "Location freshness < 3s", "Fault tolerance", "City-level scalability"],
  },
  capacity: { source: "calculated" },
  services: [
    {
      id: "mobile-clients",
      name: "Mobile Clients",
      type: "client",
      description: "Rider and driver apps.",
      responsibilities: ["Request rides", "Stream location", "Track trip"],
      technology: "iOS / Android",
      scalingStrategy: "Client-side; exponential backoff on location send.",
      failureBehavior: "Offline queue of location points with timestamps.",
    },
    {
      id: "api-gateway",
      name: "API Gateway",
      type: "gateway",
      description: "Terminates mobile APIs and websocket upgrades for tracking.",
      responsibilities: ["Auth", "Rate limit location updates", "Route"],
      technology: "Envoy",
      scalingStrategy: "Horizontal; regionally deployed.",
      failureBehavior: "Reject excess location updates before they hit Redis.",
    },
    {
      id: "auth-service",
      name: "Identity Service",
      type: "auth",
      description: "Rider/driver identity and device binding.",
      responsibilities: ["Login", "Role checks"],
      technology: "Go",
      scalingStrategy: "Stateless JWT.",
      failureBehavior: "In-flight trips continue with cached tokens.",
    },
    {
      id: "location-service",
      name: "Location Service",
      type: "service",
      description: "Ingests driver pings and maintains geo indexes.",
      responsibilities: ["Write driver location", "Query nearby drivers"],
      technology: "Go",
      scalingStrategy: "Shard Redis geo keys by geohash / city.",
      failureBehavior: "Stale locations expire via TTL; matching quality degrades.",
    },
    {
      id: "matching-service",
      name: "Matching Service",
      type: "service",
      description: "Selects a driver for a ride request under ETA and fairness constraints.",
      responsibilities: ["Candidate search", "Offer/accept", "Timeouts"],
      technology: "Java",
      scalingStrategy: "Stateless workers per city cell.",
      failureBehavior: "If matching fails, request stays unassigned and is retried.",
    },
    {
      id: "trip-service",
      name: "Trip Service",
      type: "service",
      description: "Trip state machine from requested to completed.",
      responsibilities: ["Create trip", "Status transitions", "Publish trip events"],
      technology: "Kotlin",
      scalingStrategy: "Partition by tripId; DB primary per region.",
      failureBehavior: "Persist state before notifying clients.",
    },
    {
      id: "pricing-service",
      name: "Pricing Service",
      type: "service",
      description: "Quote generation with surge based on demand/supply.",
      responsibilities: ["Upfront quote", "Final fare"],
      technology: "Python",
      scalingStrategy: "Cache surge multipliers per cell; recompute asynchronously.",
      failureBehavior: "Fall back to last known multiplier with a freshness bound.",
    },
    {
      id: "notification-service",
      name: "Notification Service",
      type: "service",
      description: "Push and websocket fan-out for trip updates.",
      responsibilities: ["Driver offers", "Rider ETAs"],
      technology: "Node.js",
      scalingStrategy: "Fan-out via Kafka consumers per channel.",
      failureBehavior: "At-least-once push; clients reconcile with trip GET.",
    },
  ],
  dataStores: [
    {
      id: "redis-geo",
      name: "Redis Geo",
      type: "cache",
      description: "Hot driver locations with TTL.",
      responsibilities: ["GEOADD", "GEORADIUS"],
      technology: "Redis",
      scalingStrategy: "Sharded by city.",
      dataCharacteristics: "High write, short TTL, lossy on restart is acceptable with fast refill.",
      failureBehavior: "Matching cannot find nearby drivers until refill.",
    },
    {
      id: "postgres",
      name: "PostgreSQL",
      type: "database",
      description: "Trips, users, ledgers for fares.",
      responsibilities: ["Trip durability", "Fare records"],
      technology: "PostgreSQL",
      scalingStrategy: "Regional primaries; read replicas for history.",
      dataCharacteristics: "Strongly consistent trip state.",
      failureBehavior: "New trips cannot start; in-memory offers may be lost.",
    },
  ],
  messageSystems: [
    {
      id: "kafka",
      name: "Kafka",
      type: "queue",
      description: "Trip events and location snapshots for analytics/tracking.",
      responsibilities: ["Trip lifecycle", "Billing events"],
      technology: "Kafka",
      scalingStrategy: "Partition by tripId / driverId.",
      failureBehavior: "Outbox on trip service; location stream may drop (locations are not source of truth).",
    },
  ],
  externalSystems: [
    {
      id: "maps",
      name: "Maps Provider",
      type: "external",
      description: "ETA, routing, geocoding.",
      responsibilities: ["Route ETA", "Map tiles"],
      technology: "Google Maps / Mapbox",
      scalingStrategy: "Cache ETAs; budget API calls.",
      failureBehavior: "Use last-known ETA heuristics; degrade map tiles.",
    },
    {
      id: "payments",
      name: "Payments",
      type: "external",
      description: "Capture rider fares.",
      responsibilities: ["Charge", "Payouts"],
      technology: "Adyen / Stripe",
      scalingStrategy: "Async capture after trip complete.",
      failureBehavior: "Trip completes; fare collection retried.",
    },
  ],
  architectureEdges: [
    { id: "r1", from: "mobile-clients", to: "api-gateway", label: "HTTPS", protocol: "HTTP" },
    { id: "r2", from: "api-gateway", to: "auth-service", label: "HTTP", protocol: "HTTP" },
    { id: "r3", from: "api-gateway", to: "location-service", label: "HTTP", protocol: "HTTP" },
    { id: "r4", from: "api-gateway", to: "matching-service", label: "HTTP", protocol: "HTTP" },
    { id: "r5", from: "api-gateway", to: "trip-service", label: "HTTP", protocol: "HTTP" },
    { id: "r6", from: "matching-service", to: "location-service", label: "gRPC", protocol: "gRPC" },
    { id: "r7", from: "matching-service", to: "pricing-service", label: "gRPC", protocol: "gRPC" },
    { id: "r8", from: "location-service", to: "redis-geo", label: "Write", protocol: "Redis" },
    { id: "r9", from: "trip-service", to: "postgres", label: "Write", protocol: "SQL" },
    { id: "r10", from: "trip-service", to: "kafka", label: "Kafka", protocol: "Kafka" },
    { id: "r11", from: "notification-service", to: "mobile-clients", label: "Push", protocol: "APNs" },
    { id: "r12", from: "kafka", to: "notification-service", label: "Async", protocol: "Kafka" },
    { id: "r13", from: "pricing-service", to: "maps", label: "HTTP", protocol: "HTTP" },
    { id: "r14", from: "trip-service", to: "payments", label: "HTTP", protocol: "HTTP" },
  ],
  apis: [
    {
      method: "POST",
      path: "/rides",
      description: "Request a ride with pickup and dropoff.",
      request: { pickup: { lat: 0, lng: 0 }, dropoff: { lat: 0, lng: 0 } },
      response: { rideId: "ride_123", status: "MATCHING", quote: { amount: 1290 } },
      authentication: "JWT",
      idempotency: "Required",
    },
    {
      method: "PUT",
      path: "/drivers/me/location",
      description: "Driver location ping.",
      request: { lat: 0, lng: 0, heading: 90 },
      response: { ok: true },
      authentication: "JWT",
      idempotency: "Not required (last-write-wins)",
    },
  ],
  dataModel: [
    {
      name: "Ride",
      fields: [
        { name: "id", type: "uuid", description: "" },
        { name: "rider_id", type: "uuid", description: "" },
        { name: "driver_id", type: "uuid", description: "Nullable until matched" },
        { name: "status", type: "enum", description: "REQUESTED|MATCHED|EN_ROUTE|COMPLETED|CANCELED" },
        { name: "quote_cents", type: "int", description: "" },
      ],
      relationships: [{ target: "LocationFix", type: "has_many", description: "Trip path" }],
    },
    {
      name: "LocationFix",
      fields: [
        { name: "driver_id", type: "uuid", description: "" },
        { name: "lat", type: "float", description: "" },
        { name: "lng", type: "float", description: "" },
        { name: "recorded_at", type: "timestamptz", description: "" },
      ],
      relationships: [],
    },
  ],
  technologyDecisions: [
    {
      technology: "Redis",
      why: "Geo queries on rapidly changing driver coordinates do not belong in PostgreSQL.",
      alternative: "PostGIS",
      whyNot: "Update rates during rush hour would dominate OLTP and still be stale.",
    },
    {
      technology: "PostgreSQL",
      why: "Trip state and money need a transactional system of record.",
      alternative: "Cassandra",
      whyNot: "Trip state machine wants strong consistency, not eventual.",
    },
    {
      technology: "Kafka",
      why: "Notifications and billing should not block matching.",
      alternative: "Synchronous push from trip service",
      whyNot: "A notification outage would stall trip transitions.",
    },
  ],
  tradeoffs: [
    {
      decision: "Location data is cached with TTL rather than fully durable",
      benefit: "Cheap high-frequency writes and fast nearby queries",
      cost: "A Redis restart creates a matching blackout until drivers ping again",
      whenToReconsider: "If regulatory tracking requires durable location history on the hot path.",
    },
    {
      decision: "Regional trip databases instead of a global primary",
      benefit: "Lower latency and blast-radius isolation per city/region",
      cost: "Cross-city trips and global analytics become harder",
      whenToReconsider: "If the product is still single-city.",
    },
  ],
  failureScenarios: [
    {
      scenario: "Redis unavailable",
      impact: "Matching cannot find drivers.",
      detection: "Geo query errors, matching p95 explosion.",
      mitigation: "Stop accepting new requests with a clear error; keep in-progress trips on Postgres.",
      recovery: "Drivers refill geo index within TTL window.",
    },
    {
      scenario: "Maps provider outage",
      impact: "ETAs and routes degrade.",
      detection: "Maps error rate, quote latency.",
      mitigation: "Haversine fallback + cached routes.",
      recovery: "Switch provider keys; keep fallback until SLO recovered.",
    },
    {
      scenario: "Matching service crash",
      impact: "New requests queue; existing trips continue.",
      detection: "Gateway 5xx to matching, unassigned ride age.",
      mitigation: "Autoscale replicas; request retry with idempotency.",
      recovery: "Reprocess unmatched rides by created_at.",
    },
    {
      scenario: "Network partition between city cells",
      impact: "Split matching views; double-offer risk.",
      detection: "Inconsistent offers, fencing errors.",
      mitigation: "Cell-affinity plus compare-and-set on driver assignment in Postgres.",
      recovery: "Fence old offers; one writer for driver assignment.",
    },
  ],
  scalingStrategy: [
    "Shard location keys by city/geohash.",
    "Keep matching workers local to a cell.",
    "Do not put location pings on the trip database.",
  ],
  securityConsiderations: [
    "Driver location is PII; restrict read APIs.",
    "Rate-limit location pings per device.",
    "Authorization separates rider vs driver roles.",
  ],
  observability: {
    metrics: [
      "Location update rate",
      "Matching latency",
      "Unassigned ride age",
      "Redis memory",
      "Trip error rate",
    ],
    logs: ["Assignment decisions with rideId/driverId", "Quote inputs without raw PII dumps"],
    traces: ["Request → matching → location → trip persist"],
    alerts: [
      "Matching p95 > 2s",
      "Location freshness > 3s for > 5% of active drivers",
      "Redis memory > 80%",
    ],
  },
});

const streaming: SystemDesign = systemDesignSchema.parse({
  title: "StreamForge Video Platform",
  summary:
    "An upload and processing pipeline plus a globally cached playback path. Masters land in object storage, transcoding workers drain a queue, and playback never touches the encode farm. Catalog and entitlements are a small control plane. Recommendations and homepage personalization are a separate read-time system so they cannot stall video start. DRM is required only for premium titles.",
  assumptions: [
    {
      name: "Requests per user per day",
      value: "30",
      rationale: "Home, search, playback session start, and sampled heartbeats — not media segment fetches.",
    },
    {
      name: "Peak multiplier",
      value: "4",
      rationale: "Prime-time viewing concentrated in a few hours.",
    },
    {
      name: "Read/write ratio",
      value: "1000:1",
      rationale: "Playback and catalog reads dwarf uploads; bytes ride the CDN, not these APIs.",
    },
    {
      name: "Storage growth",
      value: "80 TB/day of media",
      rationale: "New titles and renditions dominate; metadata is negligible by comparison.",
    },
  ],
  requirements: {
    functional: [
      "Authenticated video upload with resumable multipart transfer",
      "Multi-bitrate transcoding and packaging",
      "Adaptive bitrate playback via CDN",
      "Catalog browse and title metadata",
      "Personalized recommendations",
      "Watch history and resume position",
    ],
    nonFunctional: [
      "Global low-latency playback",
      "High availability for ready titles even when transcoding is down",
      "Cost-efficient origin egress",
      "Control plane scales independently from media path",
    ],
  },
  capacity: { source: "calculated" },
  services: [
    {
      id: "client",
      name: "Playback Client",
      type: "client",
      description: "Adaptive bitrate player and creator studio.",
      responsibilities: ["Upload", "ABR playback", "Watch history"],
      technology: "Web / mobile players",
      scalingStrategy: "Clients only; CDN for manifests and segments.",
      failureBehavior: "Player can continue from buffered segments if heartbeat fails.",
    },
    {
      id: "cdn",
      name: "CDN",
      type: "cdn",
      description: "Caches HLS/DASH segments and manifests close to viewers.",
      responsibilities: ["Segment cache", "Origin shield"],
      technology: "CloudFront",
      scalingStrategy: "Global POP cache; signed cookies for premium titles.",
      failureBehavior: "Cache misses hit origin storage; popular titles remain hot.",
    },
    {
      id: "api-gateway",
      name: "API Gateway",
      type: "gateway",
      description: "Control-plane APIs for catalog, upload URLs, and history.",
      responsibilities: ["Auth", "Signed URL minting"],
      technology: "Envoy",
      scalingStrategy: "Control plane is tiny compared to CDN bytes.",
      failureBehavior: "Playback of already-cached content continues.",
    },
    {
      id: "upload-service",
      name: "Upload Service",
      type: "service",
      description: "Issues multipart upload URLs and tracks ingest state.",
      responsibilities: ["Create upload", "Complete upload", "Enqueue transcode"],
      technology: "Go",
      scalingStrategy: "Stateless; storage does the heavy bytes.",
      failureBehavior: "Incomplete multipart uploads abort via lifecycle rules.",
    },
    {
      id: "transcode-worker",
      name: "Transcode Workers",
      type: "service",
      description: "CPU/GPU workers that produce renditions.",
      responsibilities: ["Generate bitrates", "Thumbnails", "Publish ready event"],
      technology: "FFmpeg on autoscaled workers",
      scalingStrategy: "Queue-driven autoscaling; spot-friendly.",
      failureBehavior: "Failed jobs retry; poison messages to DLQ.",
    },
    {
      id: "catalog-service",
      name: "Catalog Service",
      type: "service",
      description: "Title metadata and playback manifests pointers.",
      responsibilities: ["Metadata", "Availability windows"],
      technology: "Kotlin",
      scalingStrategy: "Read-heavy; cache + replicas.",
      failureBehavior: "CDN still has segments; new titles cannot be published.",
    },
    {
      id: "playback-service",
      name: "Playback Service",
      type: "service",
      description: "Authorizes playback and returns manifest URLs.",
      responsibilities: ["Entitlement check", "Signed URLs"],
      technology: "Go",
      scalingStrategy: "Horizontally scaled; cache entitlements briefly.",
      failureBehavior: "Deny new sessions; existing CDN cookies may continue until expiry.",
    },
    {
      id: "recs-service",
      name: "Recommendations",
      type: "service",
      description: "Home-rail ranking from offline + nearline features.",
      responsibilities: ["Rank titles", "Fallback popular list"],
      technology: "Python",
      scalingStrategy: "Precompute per user; online service is a thin lookup.",
      failureBehavior: "Fall back to trending/popular; never block playback.",
    },
  ],
  dataStores: [
    {
      id: "object-storage",
      name: "Object Storage",
      type: "storage",
      description: "Mezzanine files and rendition segments.",
      responsibilities: ["Origin for CDN", "Upload landing zone"],
      technology: "S3",
      scalingStrategy: "Lifecycle to colder tiers; partitioning by title id.",
      dataCharacteristics: "Huge sequential objects; immutable renditions.",
      failureBehavior: "Uploads fail; cached playback continues.",
    },
    {
      id: "postgres",
      name: "PostgreSQL",
      type: "database",
      description: "Catalog, users, entitlements, upload state.",
      responsibilities: ["Metadata", "History"],
      technology: "PostgreSQL",
      scalingStrategy: "Read replicas; not on the media path.",
      dataCharacteristics: "Small rows relative to video bytes.",
      failureBehavior: "Cannot mint new playback sessions.",
    },
    {
      id: "redis",
      name: "Redis",
      type: "cache",
      description: "Session, entitlement, and popular-rail cache.",
      responsibilities: ["Hot recs", "Playback auth cache"],
      technology: "Redis",
      scalingStrategy: "Cluster; TTL-based.",
      dataCharacteristics: "Lossy cache.",
      failureBehavior: "Hit Postgres; recs fall back to static popular list.",
    },
  ],
  messageSystems: [
    {
      id: "kafka",
      name: "Kafka",
      type: "queue",
      description: "Ingest and transcode job pipeline plus watch events.",
      responsibilities: ["Transcode jobs", "Watch telemetry"],
      technology: "Kafka",
      scalingStrategy: "Priority topics for premium titles; partition by titleId.",
      failureBehavior: "Uploads accepted but processing delayed; DLQ for poison jobs.",
    },
  ],
  externalSystems: [
    {
      id: "drm",
      name: "DRM License Server",
      type: "external",
      description: "Issues playback licenses for protected titles.",
      responsibilities: ["License", "Key rotation"],
      technology: "Widevine / FairPlay proxy",
      scalingStrategy: "Cache licenses where allowed.",
      failureBehavior: "Protected titles cannot start; free titles unaffected.",
    },
  ],
  architectureEdges: [
    { id: "s1", from: "client", to: "cdn", label: "HTTPS", protocol: "HTTP" },
    { id: "s2", from: "client", to: "api-gateway", label: "HTTPS", protocol: "HTTP" },
    { id: "s3", from: "cdn", to: "object-storage", label: "Read", protocol: "HTTP" },
    { id: "s4", from: "api-gateway", to: "upload-service", label: "HTTP", protocol: "HTTP" },
    { id: "s5", from: "api-gateway", to: "playback-service", label: "HTTP", protocol: "HTTP" },
    { id: "s6", from: "api-gateway", to: "catalog-service", label: "HTTP", protocol: "HTTP" },
    { id: "s7", from: "api-gateway", to: "recs-service", label: "HTTP", protocol: "HTTP" },
    { id: "s8", from: "upload-service", to: "object-storage", label: "Write", protocol: "HTTP" },
    { id: "s9", from: "upload-service", to: "kafka", label: "Kafka", protocol: "Kafka" },
    { id: "s10", from: "kafka", to: "transcode-worker", label: "Async", protocol: "Kafka" },
    { id: "s11", from: "transcode-worker", to: "object-storage", label: "Write", protocol: "HTTP" },
    { id: "s12", from: "catalog-service", to: "postgres", label: "SQL", protocol: "SQL" },
    { id: "s13", from: "playback-service", to: "redis", label: "Read", protocol: "Redis" },
    { id: "s14", from: "playback-service", to: "drm", label: "HTTP", protocol: "HTTP" },
    { id: "s15", from: "recs-service", to: "redis", label: "Read", protocol: "Redis" },
  ],
  apis: [
    {
      method: "POST",
      path: "/uploads",
      description: "Create a multipart upload and receive signed URLs.",
      request: { filename: "master.mov", contentType: "video/quicktime" },
      response: { uploadId: "up_123", urls: [] },
      authentication: "JWT",
      idempotency: "Required",
    },
    {
      method: "GET",
      path: "/playback/{titleId}",
      description: "Return entitlement and signed manifest URL.",
      request: {},
      response: { manifestUrl: "https://cdn.example/title.m3u8", drm: true },
      authentication: "JWT",
      idempotency: "Not required",
    },
  ],
  dataModel: [
    {
      name: "Title",
      fields: [
        { name: "id", type: "uuid", description: "" },
        { name: "name", type: "string", description: "" },
        { name: "status", type: "enum", description: "PROCESSING|READY|FAILED" },
      ],
      relationships: [{ target: "Rendition", type: "has_many", description: "" }],
    },
    {
      name: "Rendition",
      fields: [
        { name: "title_id", type: "uuid", description: "" },
        { name: "bitrate", type: "int", description: "kbps" },
        { name: "object_key", type: "string", description: "" },
      ],
      relationships: [{ target: "Title", type: "belongs_to", description: "" }],
    },
    {
      name: "WatchEvent",
      fields: [
        { name: "user_id", type: "uuid", description: "" },
        { name: "title_id", type: "uuid", description: "" },
        { name: "position_s", type: "int", description: "" },
      ],
      relationships: [],
    },
  ],
  technologyDecisions: [
    {
      technology: "Object storage",
      why: "Video bytes dominate cost and must sit behind a CDN, not a database.",
      alternative: "Block storage on transcode machines",
      whyNot: "Workers are ephemeral; origin must outlive them.",
    },
    {
      technology: "CDN",
      why: "Playback is a globally distributed read-mostly byte stream.",
      alternative: "Direct S3 to clients",
      whyNot: "Origin egress cost and startup latency would explode at prime time.",
    },
    {
      technology: "Kafka",
      why: "Transcoding is bursty and should absorb uploads without blocking the studio UI.",
      alternative: "Synchronous transcode API",
      whyNot: "A 4K encode can take minutes to hours.",
    },
    {
      technology: "Redis",
      why: "Entitlements and popular rails need a cheap lookup on session start.",
      alternative: "Postgres on every heartbeat",
      whyNot: "Heartbeats would drown the metadata database.",
    },
  ],
  tradeoffs: [
    {
      decision: "Playback is fully decoupled from transcoding",
      benefit: "A transcode backlog never affects streaming of ready titles",
      cost: "New titles have higher time-to-first-ready",
      whenToReconsider: "If the product is live streaming rather than VOD.",
    },
    {
      decision: "Recommendations never sit on the playback path",
      benefit: "Home-rail outages do not stop video start",
      cost: "Homepage can look generic during recs failure",
      whenToReconsider: "If the only surface is a personalized homepage with no catalog fallback.",
    },
  ],
  failureScenarios: [
    {
      scenario: "Kafka unavailable",
      impact: "Uploads succeed but transcoding stalls.",
      detection: "Producer errors, job age, worker utilization drop.",
      mitigation: "Persist job records in Postgres; retry enqueue.",
      recovery: "Drain pending jobs when Kafka returns.",
    },
    {
      scenario: "CDN origin (object storage) outage",
      impact: "Cache misses fail; hot titles may continue from POP cache.",
      detection: "Origin 5xx, cache hit ratio, playback error rate.",
      mitigation: "Origin shield, multi-AZ buckets, longer TTLs for segments.",
      recovery: "Warm popular titles after restore.",
    },
    {
      scenario: "DRM license outage",
      impact: "Protected titles cannot start.",
      detection: "License error rate.",
      mitigation: "Short license cache; communicate degraded titles.",
      recovery: "Fail over license endpoint.",
    },
    {
      scenario: "Traffic spike at prime time",
      impact: "Control-plane APIs saturate if heartbeats are naïve.",
      detection: "Playback API RPS, Redis CPU, CDN 4xx.",
      mitigation: "Heartbeat sampling, entitlement cache, CDN signed cookies.",
      recovery: "Autoscale playback service; keep media path on CDN.",
    },
  ],
  scalingStrategy: [
    "Put all media bytes on CDN + object storage.",
    "Autoscale transcode from queue depth, not from API RPS.",
    "Keep metadata DBs off the byte path.",
  ],
  securityConsiderations: [
    "Signed cookies/URLs for playback.",
    "DRM for premium titles.",
    "Upload URLs scoped to object key and expiry.",
  ],
  observability: {
    metrics: [
      "Time-to-first-frame",
      "Rebuffer ratio",
      "Transcode queue depth",
      "CDN cache hit ratio",
      "Origin egress",
    ],
    logs: ["Upload completion", "Transcode job outcome", "Playback auth denials"],
    traces: ["Playback session start", "Upload → enqueue → transcode → ready"],
    alerts: [
      "Rebuffer ratio > 2%",
      "Transcode queue age > threshold",
      "Origin error rate > 1%",
      "Playback API error rate > 2%",
    ],
  },
});

export const SEEDED_DESIGNS = [
  {
    template: DESIGN_TEMPLATES.find((t) => t.slug === "ecommerce")!,
    design: applyDeterministicCapacity(
      DESIGN_TEMPLATES.find((t) => t.slug === "ecommerce")!.input,
      ecommerce,
    ),
  },
  {
    template: DESIGN_TEMPLATES.find((t) => t.slug === "ride-sharing")!,
    design: applyDeterministicCapacity(
      DESIGN_TEMPLATES.find((t) => t.slug === "ride-sharing")!.input,
      rideshare,
    ),
  },
  {
    template: DESIGN_TEMPLATES.find((t) => t.slug === "video-streaming")!,
    design: applyDeterministicCapacity(
      DESIGN_TEMPLATES.find((t) => t.slug === "video-streaming")!.input,
      streaming,
    ),
  },
];
